
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDA")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDA", targetNamespace = "http://service/", className = "service.ConversionEuroToDA")
    @ResponseWrapper(localName = "ConversionEuroToDAResponse", targetNamespace = "http://service/", className = "service.ConversionEuroToDAResponse")
    @Action(input = "http://service/BanqueWS/ConversionEuroToDARequest", output = "http://service/BanqueWS/ConversionEuroToDAResponse")
    public double conversionEuroToDA(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service/", className = "service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service/", className = "service.GetCompteResponse")
    @Action(input = "http://service/BanqueWS/getCompteRequest", output = "http://service/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        long code);

    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompts", targetNamespace = "http://service/", className = "service.GetCompts")
    @ResponseWrapper(localName = "getComptsResponse", targetNamespace = "http://service/", className = "service.GetComptsResponse")
    @Action(input = "http://service/BanqueWS/getComptsRequest", output = "http://service/BanqueWS/getComptsResponse")
    public List<Compte> getCompts();

}
